title: "Гайды для программистов"
email: support@hexlet.io
timezone: UTC
# baseurl: ""
# url: 'https://guides.hexlet.io'

tagline: Гайды
description: |
  Полезные статьи и гайды для разработчиков

twitter:
  author: HexletHQ
  card: summary

social:
  links:
    - https://www.instagram.com/hexlethq/
    - https://www.facebook.com/Hexlet/
    - https://twitter.com/HexletHQ


permalink: "/:title/"
logo: 'assets/images/hexlet_logo.png'
favicon: 'assets/images/favicons/favicon-128.png'
author: Kirill Mokevnin
paginate: 30
disqus: hexlet-guides
locale: ru_RU
lang: ru_RU
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1

markdown: kramdown
kramdown:
  input: GFM
  # default_lang: html
  syntax_highlighter_opts:
    css_class: 'syntax'
  #   disable: true

highlighter: rouge

sass:
  # sass_dir: _sass
  load_paths:
    - _sass
    - node_modules
  # style: :compressed

ganalytics: GTM-KMJ8HKG

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  # - jekyll-github-metadata

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
